### ISSUE TITLE
Use drupol/phposinfo

### ISSUE THREAD

**Issue by drupol** [WyriHaximus/php-cpu-core-detector#29]
Hi,

It seems that tivie/php-os-detector is a dependency and it can produces false results, see the corresponding issue: https://github.com/tivie/php-os-detector/issues/3

Based on this, I've created my own package: [drupol/phposinfo](https://packagist.org/packages/drupol/phposinfo) that fixes the issue.

This issue is to propose the replacement of tivie/php-os-detector with drupol/phposinfo.

**Comment by WyriHaximus** [comment]
Sure go ahead, as mentioned at https://github.com/tivie/php-os-detector/issues/3#issuecomment-511156883 I would be interested in an example where you ran into this
